_:
{
  imports = [
    ./bindfs.nix
    ./dnsmasq.nix
    ./ejabberd
    ./folderPerms.nix
    ./hosts.nix
    ./klem.nix
    ./mysql-backup.nix
    ./news.nix
    ./nichtparasoup.nix
    ./pyload.nix
    ./restic.nix
    ./screenlock.nix
    ./sync-containers.nix
    ./usershadow.nix
    ./xjail.nix
    ./autowifi.nix
    ./browsers.nix
  ];
}
