_:
{
  imports = [
    ./dnsmasq.nix
    ./ejabberd
    ./folderPerms.nix
    ./hass.nix
    ./hosts.nix
    ./mysql-backup.nix
    ./news.nix
    ./nichtparasoup.nix
    ./pyload.nix
    ./restic.nix
    ./screenlock.nix
    ./umts.nix
    ./usershadow.nix
    ./xjail.nix
    ./autowifi.nix
    ./browsers.nix
  ];
}
