_:
{
  imports = [
    ./dnsmasq.nix
    ./drbd.nix
    ./folderPerms.nix
    ./hosts.nix
    ./klem.nix
    ./mysql-backup.nix
    ./news.nix
    ./nichtparasoup.nix
    ./pyload.nix
    ./screenlock.nix
    ./usershadow.nix
    ./xjail.nix
    ./autowifi.nix
    ./browsers.nix
    ./sync-containers3.nix
  ];
}
