#! /bin/sh
#
# usage: ./deploy HOST [[USER@]HOST]
#
set -euf

PATH="$PWD/bin${PATH+:$PATH}"
export PATH

user=root
host=$1

config=./modules/$host/default.nix
target=${2-$user@$host}

exec ssh-deploy "$config" "$target"
