#! /bin/sh
#
# usage: ./deploy HOST [TARGET]
#
set -euf

export PATH="$PWD/bin:$PATH"
#export nixpkgs=/var/nixpkgs
export nixpkgs_root=$PWD/tmp/nixpkgs
export config_root=$PWD
export retiolum_hosts=$PWD/hosts
export secrets_root=$PWD/secrets

exec nixos-deploy "$@"
