#! /bin/sh
#
# usage: ./infest cac-servername hostname
#
set -euf

PATH="$PWD/bin${PATH+:$PATH}"
export PATH

nix_url=https://nixos.org/releases/nix/nix-1.8/nix-1.8-x86_64-linux.tar.bz2
nix_sha256=52fab207b4ce4d098a12d85357d0353e972c492bab0aa9e08e1600363e76fefb
nix_find_sha1sum=86f8775bd4f0841edd4c816df861cebf509d58c3
export nix_url nix_sha256 nix_find_sha1sum

exec infest-cac "$@"
