#! /bin/sh
# usage: xdpychvt {prev,next}
# Changes to the VT based on the selected X display.
#
# This allows switching between X servers when display names and VT numbers
# correlate.  A more sophisticated tool would try to determine the correct VT
# by e.g. looking at /proc, but this might not possible when e.g.  using
# security.hideProcessInformation.
#

chvt "$(xdpysel "$1")"
