{ pkgs, ... }:

{
  krebs.newsbot-js.news-spam = {
    feeds = pkgs.writeText "feeds" ''
      [SPAM]aje|http://www.aljazeera.com/Services/Rss/?PostingId=2007731105943979989|#snews
      [SPAM]allafrica|http://allafrica.com/tools/headlines/rdf/latest/headlines.rdf|#snews
      [SPAM]antirez|http://antirez.com/rss|#snews
      [SPAM]arbor|http://feeds2.feedburner.com/asert/|#snews
      [SPAM]archlinux|http://www.archlinux.org/feeds/news/|#snews
      [SPAM]ars|http://feeds.arstechnica.com/arstechnica/index?format=xml|#snews
      [SPAM]augustl|http://augustl.com/atom.xml|#snews
      [SPAM]bbc|http://feeds.bbci.co.uk/news/rss.xml|#snews
      [SPAM]bdt_aktuelle_themen|http://www.bundestag.de/blueprint/servlet/service/de/14154/asFeed/index.rss|#snews
      [SPAM]bdt_drucksachen|http://www.bundestag.de/dip21rss/bundestag_drucksachen.rss|#snews
      [SPAM]bdt_plenarproto|http://www.bundestag.de/rss_feeds/plenarprotokolle.rss|#snews
      [SPAM]bdt_pressemitteilungen|http://www.bundestag.de/blueprint/servlet/service/de/273112/asFeed/index.rss|#snews
      [SPAM]bitcoinpakistan|https://bitcoinspakistan.com/feed/|#snews
      [SPAM]cancer|http://feeds.feedburner.com/ncinewsreleases?format=xml|#snews
      [SPAM]carta|http://feeds2.feedburner.com/carta-standard-rss|#snews
      [SPAM]catholic_news|http://feeds.feedburner.com/catholicnewsagency/dailynews|#snews
      [SPAM]cbc_busi|http://rss.cbc.ca/lineup/business.xml|#snews
      [SPAM]cbc_offbeat|http://www.cbc.ca/cmlink/rss-offbeat|#snews
      [SPAM]cbc_pol|http://rss.cbc.ca/lineup/politics.xml|#snews
      [SPAM]cbc_tech|http://rss.cbc.ca/lineup/technology.xml|#snews
      [SPAM]cbc_top|http://rss.cbc.ca/lineup/topstories.xml|#snews
      [SPAM]ccc|http://www.ccc.de/rss/updates.rdf|#snews
      [SPAM]chan_biz|http://boards.4chan.org/biz/index.rss|#snews
      [SPAM]chan_g|http://boards.4chan.org/g/index.rss|#snews
      [SPAM]chan_int|http://boards.4chan.org/int/index.rss|#snews
      [SPAM]chan_sci|http://boards.4chan.org/sci/index.rss|#snews
      [SPAM]chan_x|http://boards.4chan.org/x/index.rss|#snews
      [SPAM]c|http://www.tempolimit-lichtgeschwindigkeit.de/news.xml|#snews
      [SPAM]cryptogon|http://www.cryptogon.com/?feed=rss2|#snews
      [SPAM]csm|http://rss.csmonitor.com/feeds/csm|#snews
      [SPAM]csm_world|http://rss.csmonitor.com/feeds/world|#snews
      [SPAM]danisch|http://www.danisch.de/blog/feed/|#snews
      [SPAM]dod|http://www.defense.gov/news/afps2.xml|#snews
      [SPAM]dwn|http://deutsche-wirtschafts-nachrichten.de/feed/customfeed/|#snews
      [SPAM]ecat|http://ecat.com/feed|#snews
      [SPAM]eia_press|http://www.eia.gov/rss/press_rss.xml|#snews
      [SPAM]eia_today|http://www.eia.gov/rss/todayinenergy.xml|#snews
      [SPAM]embargowatch|https://embargowatch.wordpress.com/feed/|#snews
      [SPAM]ethereum-comments|http://blog.ethereum.org/comments/feed|#snews
      [SPAM]ethereum|http://blog.ethereum.org/feed|#snews
      [SPAM]europa_ric|http://ec.europa.eu/research/infocentre/rss/infocentre-rss.xml|#snews
      [SPAM]eu_survei|http://www.eurosurveillance.org/public/RSSFeed/RSS.aspx|#snews
      [SPAM]exploitdb|http://www.exploit-db.com/rss.xml|#snews
      [SPAM]fars|http://www.farsnews.com/rss.php|#snews #test
      [SPAM]faz_feui|http://www.faz.net/rss/aktuell/feuilleton/|#snews
      [SPAM]faz_politik|http://www.faz.net/rss/aktuell/politik/|#snews
      [SPAM]faz_wirtschaft|http://www.faz.net/rss/aktuell/wirtschaft/|#snews
      [SPAM]fbi|https://www.fbi.gov/news/rss.xml|#snews
      [SPAM]fedreserve|http://www.federalreserve.gov/feeds/press_all.xml|#snews
      [SPAM]fefe|http://blog.fefe.de/rss.xml|#snews
      [SPAM]forbes|http://www.forbes.com/forbes/feed2/|#snews
      [SPAM]forbes_realtime|http://www.forbes.com/real-time/feed2/|#snews
      [SPAM]fox|http://feeds.foxnews.com/foxnews/latest|#snews
      [SPAM]geheimorganisation|http://geheimorganisation.org/feed/|#snews
      [SPAM]GerForPol|http://www.german-foreign-policy.com/de/news/rss-2.0|#snews
      [SPAM]gmanet|http://www.gmanetwork.com/news/rss/news|#snews
      [SPAM]golem|http://rss.golem.de/rss.php|#snews
      [SPAM]google|http://news.google.com/?output=rss|#snews
      [SPAM]greenpeace|http://feeds.feedburner.com/GreenpeaceNews|#snews
      [SPAM]guardian_uk|http://feeds.theguardian.com/theguardian/uk-news/rss|#snews
      [SPAM]gulli|http://ticker.gulli.com/rss/|#snews
      [SPAM]hackernews|https://news.ycombinator.com/rss|#snews
      [SPAM]handelsblatt|http://www.handelsblatt.com/contentexport/feed/schlagzeilen|#snews
      [SPAM]heise|https://www.heise.de/newsticker/heise-atom.xml|#snews
      [SPAM]hindu_business|http://www.thehindubusinessline.com/?service=rss|#snews
      [SPAM]hindu|http://www.thehindu.com/?service=rss|#snews
      [SPAM]ign|http://feeds.ign.com/ign/all|#snews
      [SPAM]independent|http://www.independent.com/rss/headlines/|#snews
      [SPAM]indymedia|https://de.indymedia.org/rss.xml|#snews
      [SPAM]info_libera|http://www.informationliberation.com/rss.xml|#snews
      [SPAM]klagen-gegen-rundfuckbeitrag|http://klagen-gegen-rundfunkbeitrag.blogspot.com/feeds/posts/default|#snews
      [SPAM]korea_herald|http://www.koreaherald.com/rss_xml.php|#snews
      [SPAM]linuxinsider|http://www.linuxinsider.com/perl/syndication/rssfull.pl|#snews
      [SPAM]lisp|http://planet.lisp.org/rss20.xml|#snews
      [SPAM]liveleak|http://www.liveleak.com/rss|#snews
      [SPAM]lolmythesis|http://lolmythesis.com/rss|#snews
      [SPAM]LtU|http://lambda-the-ultimate.org/rss.xml|#snews
      [SPAM]lukepalmer|http://lukepalmer.wordpress.com/feed/|#snews
      [SPAM]mit|http://web.mit.edu/newsoffice/rss-feeds.feed?type=rss|#snews
      [SPAM]mongrel2_master|https://github.com/zedshaw/mongrel2/commits/master.atom|#snews
      [SPAM]nds|http://www.nachdenkseiten.de/?feed=atom|#snews
      [SPAM]netzpolitik|https://netzpolitik.org/feed/|#snews
      [SPAM]newsbtc|http://newsbtc.com/feed/|#snews
      [SPAM]nnewsg|http://www.net-news-global.net/rss/rssfeed.xml|#snews
      [SPAM]npr_busi|http://www.npr.org/rss/rss.php?id=1006|#snews
      [SPAM]npr_headlines|http://www.npr.org/rss/rss.php?id=1001|#snews
      [SPAM]npr_pol|http://www.npr.org/rss/rss.php?id=1012|#snews
      [SPAM]npr_world|http://www.npr.org/rss/rss.php?id=1004|#snews
      [SPAM]nsa|https://www.nsa.gov/rss.xml|#snews #bullerei
      [SPAM]nytimes|http://rss.nytimes.com/services/xml/rss/nyt/World.xml|#snews
      [SPAM]painload|https://github.com/krebscode/painload/commits/master.atom|#snews
      [SPAM]phys|http://phys.org/rss-feed/|#snews
      [SPAM]piraten|https://www.piratenpartei.de/feed/|#snews
      [SPAM]polizei_berlin|http://www.berlin.de/polizei/presse-fahndung/_rss_presse.xml|#snews
      [SPAM]presse_polizei|http://www.presseportal.de/rss/polizei.rss2|#snews
      [SPAM]presseportal|http://www.presseportal.de/rss/presseportal.rss2|#snews
      [SPAM]prisonplanet|http://prisonplanet.com/feed.rss|#snews
      [SPAM]rawstory|http://www.rawstory.com/rs/feed/|#snews
      [SPAM]reddit_4chan|http://www.reddit.com/r/4chan/new/.rss|#snews
      [SPAM]reddit_anticonsum|http://www.reddit.com/r/Anticonsumption/new/.rss|#snews
      [SPAM]reddit_btc|http://www.reddit.com/r/Bitcoin/new/.rss|#snews
      [SPAM]reddit_consp|http://reddit.com/r/conspiracy/.rss|#snews
      [SPAM]reddit_haskell|http://www.reddit.com/r/haskell/.rss|#snews
      [SPAM]reddit_nix|http://www.reddit.com/r/nixos/.rss|#snews
      [SPAM]reddit_prog|http://www.reddit.com/r/programming/new/.rss|#snews
      [SPAM]reddit_sci|http://www.reddit.com/r/science/.rss|#snews
      [SPAM]reddit_tech|http://www.reddit.com/r/technology/.rss|#snews
      [SPAM]reddit_tpp|http://www.reddit.com/r/twitchplayspokemon/.rss|#snews
      [SPAM]reddit_world|http://www.reddit.com/r/worldnews/.rss|#snews
      [SPAM]r-ethereum|http://www.reddit.com/r/ethereum/.rss|#snews
      [SPAM]reuters|http://feeds.reuters.com/Reuters/worldNews|#snews
      [SPAM]reuters-odd|http://feeds.reuters.com/reuters/oddlyEnoughNews?format=xml|#snews
      [SPAM]rt|http://rt.com/rss/news/|#snews
      [SPAM]schallurauch|http://feeds.feedburner.com/SchallUndRauch|#snews
      [SPAM]sciencemag|http://news.sciencemag.org/rss/current.xml|#snews
      [SPAM]scmp|http://www.scmp.com/rss/91/feed|#snews
      [SPAM]sec-db|http://feeds.security-database.com/SecurityDatabaseToolsWatch|#snews
      [SPAM]shackspace|http://blog.shackspace.de/?feed=rss2|#snews
      [SPAM]shz_news|http://www.shz.de/nachrichten/newsticker/rss|#snews
      [SPAM]sky_busi|http://feeds.skynews.com/feeds/rss/business.xml|#snews
      [SPAM]sky_pol|http://feeds.skynews.com/feeds/rss/politics.xml|#snews
      [SPAM]sky_strange|http://feeds.skynews.com/feeds/rss/strange.xml|#snews
      [SPAM]sky_tech|http://feeds.skynews.com/feeds/rss/technology.xml|#snews
      [SPAM]sky_world|http://feeds.skynews.com/feeds/rss/world.xml|#snews
      [SPAM]slashdot|http://rss.slashdot.org/Slashdot/slashdot|#snews
      [SPAM]slate|http://feeds.slate.com/slate|#snews
      [SPAM]spiegel_eil|http://www.spiegel.de/schlagzeilen/eilmeldungen/index.rss|#snews
      [SPAM]spiegelfechter|http://feeds.feedburner.com/DerSpiegelfechter?format=xml|#snews
      [SPAM]spiegel_top|http://www.spiegel.de/schlagzeilen/tops/index.rss|#snews
      [SPAM]standardmedia_ke|http://www.standardmedia.co.ke/rss/headlines.php|#snews
      [SPAM]stern|http://www.stern.de/feed/standard/all/|#snews
      [SPAM]stz|http://www.stuttgarter-zeitung.de/rss/topthemen.rss.feed|#snews
      [SPAM]sz_politik|http://rss.sueddeutsche.de/rss/Politik|#snews
      [SPAM]sz_wirtschaft|http://rss.sueddeutsche.de/rss/Wirtschaft|#snews
      [SPAM]sz_wissen|http://rss.sueddeutsche.de/rss/Wissen|#snews
      [SPAM]tagesschau|http://www.tagesschau.de/newsticker.rdf|#snews
      [SPAM]taz|http://taz.de/Themen-des-Tages/!p15;rss/|#snews
      [SPAM]telegraph|http://www.telegraph.co.uk/rss.xml|#snews
      [SPAM]telepolis|http://www.heise.de/tp/rss/news-atom.xml|#snews
      [SPAM]the_insider|http://www.theinsider.org/rss/news/headlines-xml.asp|#snews
      [SPAM]tigsource|http://www.tigsource.com/feed/|#snews
      [SPAM]tinc|http://tinc-vpn.org/news/index.rss|#snews
      [SPAM]topix_b|http://www.topix.com/rss/wire/de/berlin|#snews
      [SPAM]torr_bits|http://feeds.feedburner.com/TorrentfreakBits|#snews
      [SPAM]torrentfreak|http://feeds.feedburner.com/Torrentfreak|#snews
      [SPAM]torr_news|http://feed.torrentfreak.com/Torrentfreak/|#snews
      [SPAM]travel_warnings|http://feeds.travel.state.gov/ca/travelwarnings-alerts|#snews
      [SPAM]un_afr|http://www.un.org/apps/news/rss/rss_africa.asp|#snews
      [SPAM]un_am|http://www.un.org/apps/news/rss/rss_americas.asp|#snews
      [SPAM]un_eu|http://www.un.org/apps/news/rss/rss_europe.asp|#snews
      [SPAM]un_me|http://www.un.org/apps/news/rss/rss_mideast.asp|#snews
      [SPAM]un_pac|http://www.un.org/apps/news/rss/rss_asiapac.asp|#snews
      [SPAM]un_top|http://www.un.org/apps/news/rss/rss_top.asp|#snews
      [SPAM]us_math_society|http://www.ams.org/cgi-bin/content/news_items.cgi?rss=1|#snews
      [SPAM]vimperator|https://sites.google.com/a/vimperator.org/www/blog/posts.xml|#snews
      [SPAM]weechat|http://dev.weechat.org/feed/atom|#snews
      [SPAM]wp_world|http://feeds.washingtonpost.com/rss/rss_blogpost|#snews
      [SPAM]xkcd|https://xkcd.com/rss.xml|#snews
      [SPAM]zdnet|http://www.zdnet.com/news/rss.xml|#snews
    '';
  };
}
