#! /bin/sh
set -efu
exec >&2

hosts_srcdir=$GITHUB_HOST_SYNC_SRCDIR
hosts_worktree=${GITHUB_HOST_SYNC_WORKTREE-/tmp/hosts}
hosts_url=${GITHUB_HOST_SYNC_URL-git@github.com:krebs/hosts.git}

test -d "$hosts_worktree" || git clone "$hosts_url" "$hosts_worktree"

cd "$hosts_worktree"

git pull

rsync \
    --chmod D755,F644 \
    --delete-excluded \
    --filter 'protect .git' \
    --recursive \
    --verbose \
    "$hosts_srcdir/" \
    .

git add .

if test -n "$(git status --porcelain)"; then
  git config user.email "$LOGNAME@$(hostname)"
  git config user.name "$LOGNAME"
  git commit -m bump
  git push
fi
