#! /bin/sh
#
# usage: ./deploy system_name [target]
#
set -euf

system_name=$1
target=${2-root@$system_name}

nix-instantiate \
    --argstr system-name "$system_name" \
    --argstr deploy-target "$target" \
    --eval --json . \
  | jq -r .  \
  | sh
