# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "redis-commands-1.3.5" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.3.5.tgz";
        sha512 = "2q8pai3gf0dczb03jjig3mpaz4j2kvw8icpgf8hp4fryr3d6c0mjkvxxdmlyhainybx4zhgqsw9ghc9p986alzdzd2n2p4cxvr8b0by";
      };
    };
    "redis-parser-2.6.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.6.0.tgz";
        sha1 = "52ed09dacac108f1a631c07e9b69941e7a19504b";
      };
    };
  };
in
{
  formidable = nodeEnv.buildNodePackage {
    name = "formidable";
    packageName = "formidable";
    version = "1.2.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/formidable/-/formidable-1.2.1.tgz";
      sha512 = "1x0n2rfaiasdjbw1mm7s29z84f68c7iji7lb1gkxvpknvv6q7bwns7z55ijcf4vkh4kvis12rbgaaih49jf9lj53s30mllb1d35bkqn";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A node.js module for parsing form data, especially file uploads.";
      homepage = https://github.com/felixge/node-formidable;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
  redis = nodeEnv.buildNodePackage {
    name = "redis";
    packageName = "redis";
    version = "2.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/redis/-/redis-2.8.0.tgz";
      sha512 = "3a3044ax6qdvss83xgjfx10h5q91ls0mwgs3wpsnxcdsiipq3cnmqzsh6glyq0r7vsmpw49jp84c2jnfrhi2bgycrkd9hhhf6ia8lrk";
    };
    dependencies = [
      sources."double-ended-queue-2.1.0-0"
      sources."redis-commands-1.3.5"
      sources."redis-parser-2.6.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Redis client library";
      homepage = https://github.com/NodeRedis/node_redis;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}