{
  imports = [
    ./android-pentest.nix
    ./consoles.nix
    ./core.nix
    ./core-gui.nix
    ./dev.nix
    ./desktop.nix
    ./extra-gui.nix
    ./games.nix
    ./media.nix
    ./mobility.nix
    ./pcmanfm-extra.nix
    ./scanner-tools.nix
    ./sec.nix
    ./sec-gui.nix
    ./studio.nix
  ];
}
